"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("./theme.css");
require("./types.js");
require("./ontologies/primitives.js");
//SHAPES FIRST
// import './shapes/YourShape.js';
//THEN COMPONENTS
require("./components/Button.js");
require("./components/Input.js");
require("./components/Tabs.js");
require("./components/Switch.js");
require("./components/Checkbox.js");
require("./components/RadioGroup.js");
require("./components/Avatar.js");
require("./components/Label.js");
require("./components/Separator.js");
require("./components/Select.js");
require("./components/Collapsible.js");
require("./components/Textarea.js");
require("./components/Accordion.js");
require("./components/HoverCard.js");
require("./components/AlertDialog.js");
require("./components/Typography.js");
require("./components/Text.js");
require("./components/Heading.js");
require("./components/AspectRatio.js");
require("./components/Dialog.js");
require("./components/ScrollArea.js");
require("./components/Popover.js");
require("./components/Tooltip.js");
require("./components/Toggle.js");
require("./components/ToggleGroup.js");
require("./components/Slider.js");
require("./components/Toast.js");
require("./components/Toaster.js");
require("./components/Progress.js");
require("./components/NavigationMenu.js");
require("./components/Menubar.js");
require("./components/MultiSelect.js");
require("./components/Spinner.js");
require("./components/Breadcrumb.js");
require("./components/Drawer.js");
require("./components/IconButton.js");
require("./components/DropdownMenu.js");
require("./components/ContextMenu.js");
require("./components/Form.js");
require("./components/Toolbar.js");
require("./components/VisuallyHidden.js");
require("./hooks/use-toast.js");
//# sourceMappingURL=index.js.map